/**
 * ListSite DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListSitesParams } from "@tierfog/core/sites";

export function createListSiteRequest(overrides: Partial<ListSitesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
