/**
 * ListEligibility DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListFlRoundEligibilityParams } from "@tierfog/core/fl";

export function createListEligibilityRequest(overrides: Partial<ListFlRoundEligibilityParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
