/**
 * CreateRevoke DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RevokeDataAddressParams } from "@tierfog/core/addressing";

export function createCreateRevokeRequest(overrides: Partial<RevokeDataAddressParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
