/**
 * ExecuteListSites - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSites Use Case
 *
 * DDD: Application use case for list Site.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSitesInput, ListSitesOutput } from "../dto/site.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { SiteRepository } from "../ports";

export class ExecuteListSites {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly site: SiteRepository
  ) {}

  async execute(input: ListSitesInput): Promise<ListSitesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.sitId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.site.listSites({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSitesOutput;
  }
}
