/**
 * ExecuteGetSite - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetSite Use Case
 *
 * DDD: Application use case for get Site.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetSiteInput, GetSiteOutput } from "../dto/site.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { SiteRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetSite {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly site: SiteRepository
  ) {}

  async execute(input: GetSiteInput): Promise<GetSiteOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.sitId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).siteId) {
      throw new ValidationError("siteId is required");
    }
    const siteId = (input as any).siteId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.site.getSite({ siteId: siteId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${siteId}`);
    }

    return entity as GetSiteOutput;
  }
}
