/**
 * Handlers for Join
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TrustDomainModule } from "../dependencies/trust-ddd.dependencies.js";
import type { ApproveSphereJoinInput } from "@tierfog/services/trust";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/trust/spheres/{sphereId}/join
 * Operation: approveSphereJoin
 */
export async function approveSphereJoin(
  request: FastifyRequest<{ Params: { sphereId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TrustDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ApproveSphereJoinInput = {
    sphereId: request.params.sphereId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.joins.create.execute(input);
  return reply.code(200).send(result);
}


