/**
 * Handlers for Quarantine
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TrustDomainModule } from "../dependencies/trust-ddd.dependencies.js";
import type { ListQuarantineEventsInput, QuarantineTierInput } from "@tierfog/services/trust";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/trust/quarantine
 * Operation: listQuarantineEvents
 */
export async function listQuarantineEvents(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], active?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: TrustDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListQuarantineEventsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.quarantines.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/trust/quarantine
 * Operation: quarantineTier
 */
export async function quarantineTier(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: TrustDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: QuarantineTierInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.quarantines.get.execute(input);
  return reply.code(201).send(result);
}


