/**
 * Handlers for Release
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TrustDomainModule } from "../dependencies/trust-ddd.dependencies.js";
import type { ReleaseQuarantineInput } from "@tierfog/services/trust";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/trust/quarantine/{eventId}/release
 * Operation: releaseQuarantine
 */
export async function releaseQuarantine(
  request: FastifyRequest<{ Params: { eventId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TrustDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ReleaseQuarantineInput = {
    eventId: request.params.eventId,
  };
  const result = await deps.useCases.releases.get.execute(input);
  return reply.code(200).send(result);
}


