/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@tierfog/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAddressingDomainModule,
  buildFlDomainModule,
  buildIdentityDomainModule,
  buildJobsDomainModule,
  buildProtocolDomainModule,
  buildProvenanceDomainModule,
  buildSitesDomainModule,
  buildTiersDomainModule,
  buildTrustDomainModule,
} from "../domains/index.js";
import type {
  AddressingDomainModule,
  FlDomainModule,
  IdentityDomainModule,
  JobsDomainModule,
  ProtocolDomainModule,
  ProvenanceDomainModule,
  SitesDomainModule,
  TiersDomainModule,
  TrustDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private addressingModule: AddressingDomainModule | null = null;
  private flModule: FlDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private jobsModule: JobsDomainModule | null = null;
  private protocolModule: ProtocolDomainModule | null = null;
  private provenanceModule: ProvenanceDomainModule | null = null;
  private sitesModule: SitesDomainModule | null = null;
  private tiersModule: TiersDomainModule | null = null;
  private trustModule: TrustDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get addressing domain module
   */
  getAddressingDependencies(): AddressingDomainModule {
    if (!this.addressingModule) {
      this.addressingModule = buildAddressingDomainModule(this.dynamoClient);
    }
    return this.addressingModule;
  }

  /**
   * Get fl domain module
   */
  getFlDependencies(): FlDomainModule {
    if (!this.flModule) {
      this.flModule = buildFlDomainModule(this.dynamoClient);
    }
    return this.flModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get jobs domain module
   */
  getJobsDependencies(): JobsDomainModule {
    if (!this.jobsModule) {
      this.jobsModule = buildJobsDomainModule(this.dynamoClient);
    }
    return this.jobsModule;
  }

  /**
   * Get protocol domain module
   */
  getProtocolDependencies(): ProtocolDomainModule {
    if (!this.protocolModule) {
      this.protocolModule = buildProtocolDomainModule(this.dynamoClient);
    }
    return this.protocolModule;
  }

  /**
   * Get provenance domain module
   */
  getProvenanceDependencies(): ProvenanceDomainModule {
    if (!this.provenanceModule) {
      this.provenanceModule = buildProvenanceDomainModule(this.dynamoClient);
    }
    return this.provenanceModule;
  }

  /**
   * Get sites domain module
   */
  getSitesDependencies(): SitesDomainModule {
    if (!this.sitesModule) {
      this.sitesModule = buildSitesDomainModule(this.dynamoClient);
    }
    return this.sitesModule;
  }

  /**
   * Get tiers domain module
   */
  getTiersDependencies(): TiersDomainModule {
    if (!this.tiersModule) {
      this.tiersModule = buildTiersDomainModule(this.dynamoClient);
    }
    return this.tiersModule;
  }

  /**
   * Get trust domain module
   */
  getTrustDependencies(): TrustDomainModule {
    if (!this.trustModule) {
      this.trustModule = buildTrustDomainModule(this.dynamoClient);
    }
    return this.trustModule;
  }

  clearAddressingDependencies(): void { this.addressingModule = null; }
  clearFlDependencies(): void { this.flModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearJobsDependencies(): void { this.jobsModule = null; }
  clearProtocolDependencies(): void { this.protocolModule = null; }
  clearProvenanceDependencies(): void { this.provenanceModule = null; }
  clearSitesDependencies(): void { this.sitesModule = null; }
  clearTiersDependencies(): void { this.tiersModule = null; }
  clearTrustDependencies(): void { this.trustModule = null; }

  getAddressingDependenciesForRequest(): AddressingDomainModule {
    return this.getAddressingDependencies();
  }

  getFlDependenciesForRequest(): FlDomainModule {
    return this.getFlDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getJobsDependenciesForRequest(): JobsDomainModule {
    return this.getJobsDependencies();
  }

  getProtocolDependenciesForRequest(): ProtocolDomainModule {
    return this.getProtocolDependencies();
  }

  getProvenanceDependenciesForRequest(): ProvenanceDomainModule {
    return this.getProvenanceDependencies();
  }

  getSitesDependenciesForRequest(): SitesDomainModule {
    return this.getSitesDependencies();
  }

  getTiersDependenciesForRequest(): TiersDomainModule {
    return this.getTiersDependencies();
  }

  getTrustDependenciesForRequest(): TrustDomainModule {
    return this.getTrustDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.addressingModule = null;
    this.flModule = null;
    this.identityModule = null;
    this.jobsModule = null;
    this.protocolModule = null;
    this.provenanceModule = null;
    this.sitesModule = null;
    this.tiersModule = null;
    this.trustModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
