/**
 * Eligibility DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Eligibility DTOs
 *
 * DDD: Application DTOs for Eligibility use cases.
 */

import type { EvaluateFlRoundEligibilityRequestInput, GetFlRoundEligibilityParams, ListFlRoundEligibilityParams } from "@tierfog/core/fl/types";

export type ListFlRoundEligibilityInput = ListFlRoundEligibilityParams;

export type EvaluateFlRoundEligibilityInput = EvaluateFlRoundEligibilityRequestInput;

export type GetFlRoundEligibilityInput = GetFlRoundEligibilityParams;

export type ListFlRoundEligibilityOutput = {};

export type EvaluateFlRoundEligibilityOutput = {};

export type GetFlRoundEligibilityOutput = {};
