/**
 * Waive DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Waive DTOs
 *
 * DDD: Application DTOs for Waive use cases.
 */

import type { WaiveFlHealthGateParams, WaiveFlHealthGateRequestInput } from "@tierfog/core/fl/types";

export type WaiveFlHealthGateInput = WaiveFlHealthGateParams & WaiveFlHealthGateRequestInput;

export type WaiveFlHealthGateOutput = {};
