/**
 * Provenance DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Provenance DTOs
 *
 * DDD: Application DTOs for Provenance use cases.
 */

import type { GetArtefactProvenanceParams, ListArtefactProvenanceParams, SealArtefactProvenanceRequestInput } from "@tierfog/core/provenance/types";

export type ListArtefactProvenanceInput = ListArtefactProvenanceParams;

export type SealArtefactProvenanceInput = SealArtefactProvenanceRequestInput;

export type GetArtefactProvenanceInput = GetArtefactProvenanceParams;

export type ListArtefactProvenanceOutput = {};

export type SealArtefactProvenanceOutput = {};

export type GetArtefactProvenanceOutput = {};
