/**
 * SiteRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SiteRepository Port
 *
 * DDD: Application port for siterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetSiteInput, GetSiteOutput, ListSitesInput, ListSitesOutput, RegisterSiteInput, RegisterSiteOutput, UpdateSiteInput, UpdateSiteOutput } from "../dto/site.dto";
export interface SiteRepository {
  listSites(input: ListSitesInput): Promise<ListSitesOutput>;
  registerSite(input: RegisterSiteInput): Promise<RegisterSiteOutput>;
  getSite(input: GetSiteInput): Promise<GetSiteOutput>;
  updateSite(input: UpdateSiteInput): Promise<UpdateSiteOutput>;
}

export type { GetSiteInput, GetSiteOutput, ListSitesInput, ListSitesOutput, RegisterSiteInput, RegisterSiteOutput, UpdateSiteInput, UpdateSiteOutput } from "../dto/site.dto";
