/**
 * Routes for Provenance
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getArtefactProvenance, listArtefactProvenance, sealArtefactProvenance } from "../handlers/provenance.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function provenanceRoutes(fastify: FastifyInstance) {
  // GET /v1/provenance (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/provenance",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProvenanceDependenciesForRequest();
        await listArtefactProvenance(request, reply, deps);
      });
    }
  );


  // POST /v1/provenance (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/provenance",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProvenanceDependenciesForRequest();
        await sealArtefactProvenance(request, reply, deps);
      });
    }
  );


  // GET /v1/provenance/{provenanceId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/provenance/:provenanceId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { provenanceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProvenanceDependenciesForRequest();
        await getArtefactProvenance(request, reply, deps);
      });
    }
  );


}
