/**
 * ProvenanceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProvenanceRepository Port
 *
 * DDD: Application port for provenancerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetArtefactProvenanceInput, GetArtefactProvenanceOutput, ListArtefactProvenanceInput, ListArtefactProvenanceOutput, SealArtefactProvenanceInput, SealArtefactProvenanceOutput } from "../dto/provenance.dto";
export interface ProvenanceRepository {
  listArtefactProvenance(input: ListArtefactProvenanceInput): Promise<ListArtefactProvenanceOutput>;
  sealArtefactProvenance(input: SealArtefactProvenanceInput): Promise<SealArtefactProvenanceOutput>;
  getArtefactProvenance(input: GetArtefactProvenanceInput): Promise<GetArtefactProvenanceOutput>;
}

export type { GetArtefactProvenanceInput, GetArtefactProvenanceOutput, ListArtefactProvenanceInput, ListArtefactProvenanceOutput, SealArtefactProvenanceInput, SealArtefactProvenanceOutput } from "../dto/provenance.dto";
