/**
 * ListQuarantine DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListQuarantineEventsParams } from "@tierfog/core/trust";

export function createListQuarantineRequest(overrides: Partial<ListQuarantineEventsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
