/**
 * CreateRelease DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ReleaseQuarantineParams } from "@tierfog/core/trust";

export function createCreateReleaseRequest(overrides: Partial<ReleaseQuarantineParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
