/**
 * JobRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * JobRepository Port
 *
 * DDD: Application port for jobrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetAnalyticsJobInput, GetAnalyticsJobOutput, ListAnalyticsJobsInput, ListAnalyticsJobsOutput, ScheduleAnalyticsJobInput, ScheduleAnalyticsJobOutput } from "../dto/job.dto";
export interface JobRepository {
  listAnalyticsJobs(input: ListAnalyticsJobsInput): Promise<ListAnalyticsJobsOutput>;
  scheduleAnalyticsJob(input: ScheduleAnalyticsJobInput): Promise<ScheduleAnalyticsJobOutput>;
  getAnalyticsJob(input: GetAnalyticsJobInput): Promise<GetAnalyticsJobOutput>;
}

export type { GetAnalyticsJobInput, GetAnalyticsJobOutput, ListAnalyticsJobsInput, ListAnalyticsJobsOutput, ScheduleAnalyticsJobInput, ScheduleAnalyticsJobOutput } from "../dto/job.dto";
