/**
 * OverridePlacementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverridePlacementRepository Port
 *
 * DDD: Application port for overrideplacementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { OverrideJobPlacementInput, OverrideJobPlacementOutput } from "../dto/override-placement.dto";
export interface OverridePlacementRepository {
  overrideJobPlacement(input: OverrideJobPlacementInput): Promise<OverrideJobPlacementOutput>;
}

export type { OverrideJobPlacementInput, OverrideJobPlacementOutput } from "../dto/override-placement.dto";
