/**
 * ExecuteReleaseQuarantine - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteReleaseQuarantine Use Case
 *
 * DDD: Application use case for get Release.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ReleaseQuarantineInput, ReleaseQuarantineOutput } from "../dto/release.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { ReleaseRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteReleaseQuarantine {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly release: ReleaseRepository
  ) {}

  async execute(input: ReleaseQuarantineInput): Promise<ReleaseQuarantineOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.trsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).eventId) {
      throw new ValidationError("eventId is required");
    }
    const eventId = (input as any).eventId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.release.releaseQuarantine({ eventId: eventId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${eventId}`);
    }

    return entity as ReleaseQuarantineOutput;
  }
}
