/**
 * ExecuteQuarantineTier - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteQuarantineTier Use Case
 *
 * DDD: Application use case for get Quarantine.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { QuarantineTierInput, QuarantineTierOutput } from "../dto/quarantine.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { QuarantineRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteQuarantineTier {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly quarantine: QuarantineRepository
  ) {}

  async execute(input: QuarantineTierInput): Promise<QuarantineTierOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.trsId();

    // All field names extracted from OpenAPI spec: continueParentDag, reason, tierId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).tierId) {
      throw new ValidationError("tierId is required");
    }
    const tierId = (input as any).tierId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.quarantine.quarantineTier({ tierId: tierId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${tierId}`);
    }

    return entity as QuarantineTierOutput;
  }
}
