/**
 * ExecuteListTrustSpheres - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListTrustSpheres Use Case
 *
 * DDD: Application use case for list Sphere.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListTrustSpheresInput, ListTrustSpheresOutput } from "../dto/sphere.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { SphereRepository } from "../ports";

export class ExecuteListTrustSpheres {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly sphere: SphereRepository
  ) {}

  async execute(input: ListTrustSpheresInput): Promise<ListTrustSpheresOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.trsId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.sphere.listTrustSpheres({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListTrustSpheresOutput;
  }
}
