/**
 * ExecuteCreateTenantSphere - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateTenantSphere Use Case
 *
 * DDD: Application use case for create Tenant.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateTenantSphereInput, CreateTenantSphereOutput } from "../dto/tenant.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { TenantRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateTenantSphere {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly tenant: TenantRepository
  ) {}

  async execute(input: CreateTenantSphereInput): Promise<CreateTenantSphereOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.trsId();

    // All field names extracted from OpenAPI spec: hostTierId, name
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.hostTierId) {
      throw new ValidationError("hostTierId is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (trust domain)
    const entityId = this.idGenerator.trsId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.tenant.createTenantSphere({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateTenantSphereOutput;
  }
}
