/**
 * ListDomain DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListProtocolDomainsParams } from "@tierfog/core/protocol";

export function createListDomainRequest(overrides: Partial<ListProtocolDomainsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
