/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { domainRoutes } from "./domain.routes.js";
export { gatewayConfigRoutes } from "./gateway-config.routes.js";
export { isolationRoutes } from "./isolation.routes.js";
