/**
 * Routes for Isolation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { updateIsolationPolicy } from "../handlers/isolation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function isolationRoutes(fastify: FastifyInstance) {
  // PUT /v1/domains/{domainId}/isolation (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/domains/:domainId/isolation",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { domainId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProtocolDependenciesForRequest();
        await updateIsolationPolicy(request, reply, deps);
      });
    }
  );


}
