/**
 * Protocol DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Protocol Domain Module - Composition root
 *
 * DDD: Composition root for protocol domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DomainRepositoryAdapter,
  GatewayConfigRepositoryAdapter,
  IsolationRepositoryAdapter,
} from "@tierfog/adapters/protocol";
import { getIdGeneratorService } from "@tierfog/adapters";
import type { AdapterDynamoDBClient } from "@tierfog/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetProtocolDomain,
  ExecuteListProtocolDomains,
  ExecuteOnboardProtocolDomain,
  ExecutePushGatewayConfig,
  ExecuteUpdateIsolationPolicy,
} from "@tierfog/services/protocol/usecases";
// Ports (interfaces)
import type {
  DomainRepository,
  GatewayConfigRepository,
  IsolationRepository,
} from "@tierfog/services/protocol/ports";

export interface ProtocolDomainModule {
  repos: {
    domains: DomainRepository;
    gatewayConfigs: GatewayConfigRepository;
    isolations: IsolationRepository;
  };
  useCases: {
    domains: {
      get: ExecuteGetProtocolDomain;
      list: ExecuteListProtocolDomains;
    };
    gatewayConfigs: {
      get: ExecutePushGatewayConfig;
    };
    isolations: {
      update: ExecuteUpdateIsolationPolicy;
    };
  };
}

export function buildProtocolDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ProtocolDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      domains?: DomainRepository;
      gatewayConfigs?: GatewayConfigRepository;
      isolations?: IsolationRepository;
    } = {};

    obj.domains = new DomainRepositoryAdapter(dynamoClient);
    obj.gatewayConfigs = new GatewayConfigRepositoryAdapter(dynamoClient);
    obj.isolations = new IsolationRepositoryAdapter(dynamoClient);
    return {
      domains: obj.domains!,
      gatewayConfigs: obj.gatewayConfigs!,
      isolations: obj.isolations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    domains: {
      get: new ExecuteGetProtocolDomain(executionContext, idGenerator, repos.domains),
      list: new ExecuteListProtocolDomains(executionContext, idGenerator, repos.domains),
    },
    gatewayConfigs: {
      get: new ExecutePushGatewayConfig(executionContext, idGenerator, repos.gatewayConfigs),
    },
    isolations: {
      update: new ExecuteUpdateIsolationPolicy(executionContext, idGenerator, repos.isolations),
    },
  };
  return { repos, useCases: useCases as ProtocolDomainModule["useCases"] };
}
