/**
 * Site Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SiteEntity } from "@tierfog/core/sites/models/index.js";
import { sitesSchemas } from "@tierfog/core/sites";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "sit";

export function createSite(overrides: Partial<SiteEntity> = {}) {
  const raw = {
    id: overrides.id ?? `sit_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    name: overrides.name ?? faker.person.fullName(),
    siteClass: overrides.siteClass ?? "hospital",
    ...overrides,
  };

  return sitesSchemas.Site.parse(raw);
}

export function siteBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSite(overrides));
}
