/**
 * TierRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TierRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TierRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TierRepository,
} from "@tierfog/services/tiers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TierRepositoryDdb } from "./tier-repository.ddb.js";

/**
 * TierRepositoryAdapter
 *
 * Implements TierRepository port for infrastructure layer.
 */
export class TierRepositoryAdapter implements TierRepository {
  private readonly ddb: TierRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TierRepositoryDdb(this.dynamoClient);
  }

  async listTiers(input: Parameters<TierRepository['listTiers']>[0]): Promise<Awaited<ReturnType<TierRepository['listTiers']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTiers(input);
  }

  async registerTier(input: Parameters<TierRepository['registerTier']>[0]): Promise<Awaited<ReturnType<TierRepository['registerTier']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerTier(input);
  }

  async getTier(input: Parameters<TierRepository['getTier']>[0]): Promise<Awaited<ReturnType<TierRepository['getTier']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getTier(input);
  }
}
