/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { jobRoutes } from "./job.routes.js";
export { overridePlacementRoutes } from "./override-placement.routes.js";
export { pauseRoutes } from "./pause.routes.js";
