/**
 * Routes for Job
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getAnalyticsJob, listAnalyticsJobs, scheduleAnalyticsJob } from "../handlers/job.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function jobRoutes(fastify: FastifyInstance) {
  // GET /v1/jobs (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/jobs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getJobsDependenciesForRequest();
        await listAnalyticsJobs(request, reply, deps);
      });
    }
  );


  // POST /v1/jobs (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/jobs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getJobsDependenciesForRequest();
        await scheduleAnalyticsJob(request, reply, deps);
      });
    }
  );


  // GET /v1/jobs/{jobId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/jobs/:jobId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { jobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getJobsDependenciesForRequest();
        await getAnalyticsJob(request, reply, deps);
      });
    }
  );


}
