/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as addressingRoutes from "../../domains/addressing/routes/index.js";
import * as flRoutes from "../../domains/fl/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as jobsRoutes from "../../domains/jobs/routes/index.js";
import * as protocolRoutes from "../../domains/protocol/routes/index.js";
import * as provenanceRoutes from "../../domains/provenance/routes/index.js";
import * as sitesRoutes from "../../domains/sites/routes/index.js";
import * as tiersRoutes from "../../domains/tiers/routes/index.js";
import * as trustRoutes from "../../domains/trust/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "addressing", mod: addressingRoutes },
  { domain: "fl", mod: flRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "jobs", mod: jobsRoutes },
  { domain: "protocol", mod: protocolRoutes },
  { domain: "provenance", mod: provenanceRoutes },
  { domain: "sites", mod: sitesRoutes },
  { domain: "tiers", mod: tiersRoutes },
  { domain: "trust", mod: trustRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
