/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@tierfog/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "addressing", "fl", "identity", "jobs", "protocol", "provenance", "sites", "tiers", "trust"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      addressing: [{ method: "GET", path: "/v1/addresses" }, { method: "POST", path: "/v1/addresses" }, { method: "POST", path: "/v1/addresses/:addressId/grant" }, { method: "POST", path: "/v1/addresses/:addressId/revoke" }],
      fl: [{ method: "GET", path: "/v1/fl/eligibility" }, { method: "POST", path: "/v1/fl/eligibility" }, { method: "GET", path: "/v1/fl/eligibility/:eligibilityId" }, { method: "POST", path: "/v1/fl/eligibility/:eligibilityId/waive" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      jobs: [{ method: "GET", path: "/v1/jobs" }, { method: "POST", path: "/v1/jobs" }, { method: "GET", path: "/v1/jobs/:jobId" }, { method: "POST", path: "/v1/jobs/:jobId/override-placement" }, { method: "POST", path: "/v1/jobs/:jobId/pause" }],
      protocol: [{ method: "GET", path: "/v1/domains" }, { method: "POST", path: "/v1/domains" }, { method: "GET", path: "/v1/domains/:domainId" }, { method: "POST", path: "/v1/domains/:domainId/gateway-config" }, { method: "PUT", path: "/v1/domains/:domainId/isolation" }],
      provenance: [{ method: "GET", path: "/v1/provenance" }, { method: "POST", path: "/v1/provenance" }, { method: "GET", path: "/v1/provenance/:provenanceId" }],
      sites: [{ method: "GET", path: "/v1/sites" }, { method: "POST", path: "/v1/sites" }, { method: "GET", path: "/v1/sites/:siteId" }, { method: "PATCH", path: "/v1/sites/:siteId" }],
      tiers: [{ method: "GET", path: "/v1/tiers" }, { method: "POST", path: "/v1/tiers" }, { method: "GET", path: "/v1/tiers/:tierId" }],
      trust: [{ method: "GET", path: "/v1/trust/spheres" }, { method: "POST", path: "/v1/trust/spheres" }, { method: "POST", path: "/v1/trust/spheres/:sphereId/join" }, { method: "GET", path: "/v1/trust/quarantine" }, { method: "POST", path: "/v1/trust/quarantine" }, { method: "POST", path: "/v1/trust/quarantine/:eventId/release" }, { method: "GET", path: "/v1/trust/tenants" }, { method: "POST", path: "/v1/trust/tenants" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
