/**
 * ExecuteUpdateIsolationPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateIsolationPolicy Use Case
 *
 * DDD: Application use case for update Isolation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateIsolationPolicyInput, UpdateIsolationPolicyOutput } from "../dto/isolation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { IsolationRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateIsolationPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly isolation: IsolationRepository
  ) {}

  async execute(input: UpdateIsolationPolicyInput): Promise<UpdateIsolationPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prdId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).domainId) {
      throw new ValidationError("domainId is required");
    }
    const domainId = (input as any).domainId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.isolation.updateIsolationPolicy({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateIsolationPolicyOutput;
  }
}
