/**
 * ExecutePushGatewayConfig - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePushGatewayConfig Use Case
 *
 * DDD: Application use case for get GatewayConfig.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PushGatewayConfigInput, PushGatewayConfigOutput } from "../dto/gateway-config.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { GatewayConfigRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePushGatewayConfig {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly gatewayConfig: GatewayConfigRepository
  ) {}

  async execute(input: PushGatewayConfigInput): Promise<PushGatewayConfigOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prdId();

    // All field names extracted from OpenAPI spec: configVersion, rolloutRing
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).domainId) {
      throw new ValidationError("domainId is required");
    }
    const domainId = (input as any).domainId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.gatewayConfig.pushGatewayConfig({ domainId: domainId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${domainId}`);
    }

    return entity as PushGatewayConfigOutput;
  }
}
