/**
 * ExecuteListProtocolDomains - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListProtocolDomains Use Case
 *
 * DDD: Application use case for list Domain.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListProtocolDomainsInput, ListProtocolDomainsOutput } from "../dto/domain.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { DomainRepository } from "../ports";

export class ExecuteListProtocolDomains {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly domain: DomainRepository
  ) {}

  async execute(input: ListProtocolDomainsInput): Promise<ListProtocolDomainsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prdId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.domain.listProtocolDomains({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListProtocolDomainsOutput;
  }
}
