/**
 * Handlers for Provenance
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProvenanceDomainModule } from "../dependencies/provenance-ddd.dependencies.js";
import type { GetArtefactProvenanceInput, ListArtefactProvenanceInput, SealArtefactProvenanceInput } from "@tierfog/services/provenance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/provenance
 * Operation: listArtefactProvenance
 */
export async function listArtefactProvenance(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], tierId?: string | string[], jobId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ProvenanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListArtefactProvenanceInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.provenances.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/provenance
 * Operation: sealArtefactProvenance
 */
export async function sealArtefactProvenance(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ProvenanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SealArtefactProvenanceInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.provenances.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/provenance/{provenanceId}
 * Operation: getArtefactProvenance
 */
export async function getArtefactProvenance(
  request: FastifyRequest<{ Params: { provenanceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProvenanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetArtefactProvenanceInput = {
    provenanceId: request.params.provenanceId,
  };
  const result = await deps.useCases.provenances.get.execute(input);
  return reply.code(200).send(result);
}


