/**
 * Jobs DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Jobs Domain Module - Composition root
 *
 * DDD: Composition root for jobs domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  JobRepositoryAdapter,
  OverridePlacementRepositoryAdapter,
  PauseRepositoryAdapter,
} from "@tierfog/adapters/jobs";
import { getIdGeneratorService } from "@tierfog/adapters";
import type { AdapterDynamoDBClient } from "@tierfog/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetAnalyticsJob,
  ExecuteListAnalyticsJobs,
  ExecuteOverrideJobPlacement,
  ExecutePauseAnalyticsJob,
  ExecuteScheduleAnalyticsJob,
} from "@tierfog/services/jobs/usecases";
// Ports (interfaces)
import type {
  JobRepository,
  OverridePlacementRepository,
  PauseRepository,
} from "@tierfog/services/jobs/ports";

export interface JobsDomainModule {
  repos: {
    jobs: JobRepository;
    overridePlacements: OverridePlacementRepository;
    pauses: PauseRepository;
  };
  useCases: {
    jobs: {
      get: ExecuteGetAnalyticsJob;
      list: ExecuteListAnalyticsJobs;
    };
    overridePlacements: {
      get: ExecuteOverrideJobPlacement;
    };
    pauses: {
      get: ExecutePauseAnalyticsJob;
    };
  };
}

export function buildJobsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): JobsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      jobs?: JobRepository;
      overridePlacements?: OverridePlacementRepository;
      pauses?: PauseRepository;
    } = {};

    obj.jobs = new JobRepositoryAdapter(dynamoClient);
    obj.overridePlacements = new OverridePlacementRepositoryAdapter(dynamoClient);
    obj.pauses = new PauseRepositoryAdapter(dynamoClient);
    return {
      jobs: obj.jobs!,
      overridePlacements: obj.overridePlacements!,
      pauses: obj.pauses!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    jobs: {
      get: new ExecuteGetAnalyticsJob(executionContext, idGenerator, repos.jobs),
      list: new ExecuteListAnalyticsJobs(executionContext, idGenerator, repos.jobs),
    },
    overridePlacements: {
      get: new ExecuteOverrideJobPlacement(executionContext, idGenerator, repos.overridePlacements),
    },
    pauses: {
      get: new ExecutePauseAnalyticsJob(executionContext, idGenerator, repos.pauses),
    },
  };
  return { repos, useCases: useCases as JobsDomainModule["useCases"] };
}
