/**
 * EligibilityRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EligibilityRepository Port
 *
 * DDD: Application port for eligibilityrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { EvaluateFlRoundEligibilityInput, EvaluateFlRoundEligibilityOutput, GetFlRoundEligibilityInput, GetFlRoundEligibilityOutput, ListFlRoundEligibilityInput, ListFlRoundEligibilityOutput } from "../dto/eligibility.dto";
export interface EligibilityRepository {
  listFlRoundEligibility(input: ListFlRoundEligibilityInput): Promise<ListFlRoundEligibilityOutput>;
  evaluateFlRoundEligibility(input: EvaluateFlRoundEligibilityInput): Promise<EvaluateFlRoundEligibilityOutput>;
  getFlRoundEligibility(input: GetFlRoundEligibilityInput): Promise<GetFlRoundEligibilityOutput>;
}

export type { EvaluateFlRoundEligibilityInput, EvaluateFlRoundEligibilityOutput, GetFlRoundEligibilityInput, GetFlRoundEligibilityOutput, ListFlRoundEligibilityInput, ListFlRoundEligibilityOutput } from "../dto/eligibility.dto";
