/**
 * WaiveRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WaiveRepository Port
 *
 * DDD: Application port for waiverepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { WaiveFlHealthGateInput, WaiveFlHealthGateOutput } from "../dto/waive.dto";
export interface WaiveRepository {
  waiveFlHealthGate(input: WaiveFlHealthGateInput): Promise<WaiveFlHealthGateOutput>;
}

export type { WaiveFlHealthGateInput, WaiveFlHealthGateOutput } from "../dto/waive.dto";
