/**
 * AddressRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AddressRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AddressRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AddressRepository,
} from "@tierfog/services/addressing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AddressRepositoryDdb } from "./address-repository.ddb.js";

/**
 * AddressRepositoryAdapter
 *
 * Implements AddressRepository port for infrastructure layer.
 */
export class AddressRepositoryAdapter implements AddressRepository {
  private readonly ddb: AddressRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AddressRepositoryDdb(this.dynamoClient);
  }

  async listDataAddresses(input: Parameters<AddressRepository['listDataAddresses']>[0]): Promise<Awaited<ReturnType<AddressRepository['listDataAddresses']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDataAddresses(input);
  }

  async registerDataAddress(input: Parameters<AddressRepository['registerDataAddress']>[0]): Promise<Awaited<ReturnType<AddressRepository['registerDataAddress']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerDataAddress(input);
  }
}
