/**
 * RevokeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RevokeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RevokeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RevokeRepository,
} from "@tierfog/services/addressing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RevokeRepositoryDdb } from "./revoke-repository.ddb.js";

/**
 * RevokeRepositoryAdapter
 *
 * Implements RevokeRepository port for infrastructure layer.
 */
export class RevokeRepositoryAdapter implements RevokeRepository {
  private readonly ddb: RevokeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RevokeRepositoryDdb(this.dynamoClient);
  }

  async revokeDataAddress(input: Parameters<RevokeRepository['revokeDataAddress']>[0]): Promise<Awaited<ReturnType<RevokeRepository['revokeDataAddress']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.revokeDataAddress(input);
  }
}
