/**
 * Handlers for GatewayConfig
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProtocolDomainModule } from "../dependencies/protocol-ddd.dependencies.js";
import type { PushGatewayConfigInput } from "@tierfog/services/protocol";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/domains/{domainId}/gateway-config
 * Operation: pushGatewayConfig
 */
export async function pushGatewayConfig(
  request: FastifyRequest<{ Params: { domainId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProtocolDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: PushGatewayConfigInput = {
    domainId: request.params.domainId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.gatewayConfigs.get.execute(input);
  return reply.code(200).send(result);
}


