/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./domain.handlers.js";
export * from "./gateway-config.handlers.js";
export * from "./isolation.handlers.js";
