/**
 * JobRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * JobRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements JobRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  JobRepository,
} from "@tierfog/services/jobs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { JobRepositoryDdb } from "./job-repository.ddb.js";

/**
 * JobRepositoryAdapter
 *
 * Implements JobRepository port for infrastructure layer.
 */
export class JobRepositoryAdapter implements JobRepository {
  private readonly ddb: JobRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new JobRepositoryDdb(this.dynamoClient);
  }

  async listAnalyticsJobs(input: Parameters<JobRepository['listAnalyticsJobs']>[0]): Promise<Awaited<ReturnType<JobRepository['listAnalyticsJobs']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAnalyticsJobs(input);
  }

  async scheduleAnalyticsJob(input: Parameters<JobRepository['scheduleAnalyticsJob']>[0]): Promise<Awaited<ReturnType<JobRepository['scheduleAnalyticsJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.scheduleAnalyticsJob(input);
  }

  async getAnalyticsJob(input: Parameters<JobRepository['getAnalyticsJob']>[0]): Promise<Awaited<ReturnType<JobRepository['getAnalyticsJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAnalyticsJob(input);
  }
}
