/**
 * OverridePlacementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverridePlacementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OverridePlacementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OverridePlacementRepository,
} from "@tierfog/services/jobs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OverridePlacementRepositoryDdb } from "./override-placement-repository.ddb.js";

/**
 * OverridePlacementRepositoryAdapter
 *
 * Implements OverridePlacementRepository port for infrastructure layer.
 */
export class OverridePlacementRepositoryAdapter implements OverridePlacementRepository {
  private readonly ddb: OverridePlacementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OverridePlacementRepositoryDdb(this.dynamoClient);
  }

  async overrideJobPlacement(input: Parameters<OverridePlacementRepository['overrideJobPlacement']>[0]): Promise<Awaited<ReturnType<OverridePlacementRepository['overrideJobPlacement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.overrideJobPlacement(input);
  }
}
