/**
 * GrantRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GrantRepository Port
 *
 * DDD: Application port for grantrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GrantDataAddressResolveInput, GrantDataAddressResolveOutput } from "../dto/grant.dto";
export interface GrantRepository {
  grantDataAddressResolve(input: GrantDataAddressResolveInput): Promise<GrantDataAddressResolveOutput>;
}

export type { GrantDataAddressResolveInput, GrantDataAddressResolveOutput } from "../dto/grant.dto";
