/**
 * Job DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Job DTOs
 *
 * DDD: Application DTOs for Job use cases.
 */

import type { GetAnalyticsJobParams, ListAnalyticsJobsParams, ScheduleAnalyticsJobRequestInput } from "@tierfog/core/jobs/types";

export type ListAnalyticsJobsInput = ListAnalyticsJobsParams;

export type ScheduleAnalyticsJobInput = ScheduleAnalyticsJobRequestInput;

export type GetAnalyticsJobInput = GetAnalyticsJobParams;

export type ListAnalyticsJobsOutput = {};

export type ScheduleAnalyticsJobOutput = {};

export type GetAnalyticsJobOutput = {};
