/**
 * OverridePlacement DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverridePlacement DTOs
 *
 * DDD: Application DTOs for OverridePlacement use cases.
 */

import type { OverrideJobPlacementParams, OverrideJobPlacementRequestInput } from "@tierfog/core/jobs/types";

export type OverrideJobPlacementInput = OverrideJobPlacementParams & OverrideJobPlacementRequestInput;

export type OverrideJobPlacementOutput = {};
