/**
 * Pause DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pause DTOs
 *
 * DDD: Application DTOs for Pause use cases.
 */

import type { PauseAnalyticsJobParams } from "@tierfog/core/jobs/types";

export type PauseAnalyticsJobInput = PauseAnalyticsJobParams;

export type PauseAnalyticsJobOutput = {};
