/**
 * Tiers DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Tiers Domain Module - Composition root
 *
 * DDD: Composition root for tiers domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  TierRepositoryAdapter,
} from "@tierfog/adapters/tiers";
import { getIdGeneratorService } from "@tierfog/adapters";
import type { AdapterDynamoDBClient } from "@tierfog/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetTier,
  ExecuteListTiers,
  ExecuteRegisterTier,
} from "@tierfog/services/tiers/usecases";
// Ports (interfaces)
import type {
  TierRepository,
} from "@tierfog/services/tiers/ports";

export interface TiersDomainModule {
  repos: {
    tiers: TierRepository;
  };
  useCases: {
    tiers: {
      create: ExecuteRegisterTier;
      get: ExecuteGetTier;
      list: ExecuteListTiers;
    };
  };
}

export function buildTiersDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TiersDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      tiers?: TierRepository;
    } = {};

    obj.tiers = new TierRepositoryAdapter(dynamoClient);
    return {
      tiers: obj.tiers!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    tiers: {
      create: new ExecuteRegisterTier(executionContext, idGenerator, repos.tiers),
      get: new ExecuteGetTier(executionContext, idGenerator, repos.tiers),
      list: new ExecuteListTiers(executionContext, idGenerator, repos.tiers),
    },
  };
  return { repos, useCases: useCases as TiersDomainModule["useCases"] };
}
