/**
 * GetProtocolDomain handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getProtocolDomain } from "@tierfog/api-server/domains/protocol/handlers";
import type { ProtocolDDDDependencies } from "@tierfog/api-server/domains/protocol";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tierfog/tests/shared";
import { PROTOCOL_USE_CASES } from "../__factories__/use-cases.js";

describe("GetProtocolDomain", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProtocolDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProtocolDDDDependencies>(
      PROTOCOL_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetProtocolDomain, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { domainId: entity.id };

    await getProtocolDomain(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetProtocolDomain.execute).toHaveBeenCalledWith(expect.objectContaining({ domainId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { domainId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetProtocolDomain, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getProtocolDomain(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
