/**
 * DomainRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DomainRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DomainRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DomainRepository,
} from "@tierfog/services/protocol";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DomainRepositoryDdb } from "./domain-repository.ddb.js";

/**
 * DomainRepositoryAdapter
 *
 * Implements DomainRepository port for infrastructure layer.
 */
export class DomainRepositoryAdapter implements DomainRepository {
  private readonly ddb: DomainRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DomainRepositoryDdb(this.dynamoClient);
  }

  async listProtocolDomains(input: Parameters<DomainRepository['listProtocolDomains']>[0]): Promise<Awaited<ReturnType<DomainRepository['listProtocolDomains']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listProtocolDomains(input);
  }

  async onboardProtocolDomain(input: Parameters<DomainRepository['onboardProtocolDomain']>[0]): Promise<Awaited<ReturnType<DomainRepository['onboardProtocolDomain']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.onboardProtocolDomain(input);
  }

  async getProtocolDomain(input: Parameters<DomainRepository['getProtocolDomain']>[0]): Promise<Awaited<ReturnType<DomainRepository['getProtocolDomain']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getProtocolDomain(input);
  }
}
