/**
 * GatewayConfigRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GatewayConfigRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GatewayConfigRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GatewayConfigRepository,
} from "@tierfog/services/protocol";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GatewayConfigRepositoryDdb } from "./gateway-config-repository.ddb.js";

/**
 * GatewayConfigRepositoryAdapter
 *
 * Implements GatewayConfigRepository port for infrastructure layer.
 */
export class GatewayConfigRepositoryAdapter implements GatewayConfigRepository {
  private readonly ddb: GatewayConfigRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GatewayConfigRepositoryDdb(this.dynamoClient);
  }

  async pushGatewayConfig(input: Parameters<GatewayConfigRepository['pushGatewayConfig']>[0]): Promise<Awaited<ReturnType<GatewayConfigRepository['pushGatewayConfig']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.pushGatewayConfig(input);
  }
}
