/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./domain-repository.ddb.js";
export * from "./gateway-config-repository.ddb.js";
export * from "./isolation-repository.ddb.js";
export * from "./domain-repository.adapter.js";
export * from "./gateway-config-repository.adapter.js";
export * from "./isolation-repository.adapter.js";
