/**
 * IsolationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IsolationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements IsolationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  IsolationRepository,
} from "@tierfog/services/protocol";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { IsolationRepositoryDdb } from "./isolation-repository.ddb.js";

/**
 * IsolationRepositoryAdapter
 *
 * Implements IsolationRepository port for infrastructure layer.
 */
export class IsolationRepositoryAdapter implements IsolationRepository {
  private readonly ddb: IsolationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new IsolationRepositoryDdb(this.dynamoClient);
  }

  async updateIsolationPolicy(input: Parameters<IsolationRepository['updateIsolationPolicy']>[0]): Promise<Awaited<ReturnType<IsolationRepository['updateIsolationPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateIsolationPolicy(input);
  }
}
