/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @tierfog/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@tierfog/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@tierfog/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@tierfog/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@tierfog/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@tierfog/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _addressing from "./addressing/index.js";
import * as _fl from "./fl/index.js";
import * as _identity from "./identity/index.js";
import * as _jobs from "./jobs/index.js";
import * as _protocol from "./protocol/index.js";
import * as _provenance from "./provenance/index.js";
import * as _sites from "./sites/index.js";
import * as _tiers from "./tiers/index.js";
import * as _trust from "./trust/index.js";

// Export as namespaces
export const _shared = __shared;
export const addressing = _addressing;
export const fl = _fl;
export const identity = _identity;
export const jobs = _jobs;
export const protocol = _protocol;
export const provenance = _provenance;
export const sites = _sites;
export const tiers = _tiers;
export const trust = _trust;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@tierfog/core"; activity.types.*
//   - Direct exports: import * from "@tierfog/core/activity/types/index.js"
//   - Direct exports: import * from "@tierfog/core/activity/repositories/index.js"
//   - Direct exports: import * from "@tierfog/core/activity/models/index.js"
//   - Direct exports: import * from "@tierfog/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Addressing Service
export { schemas as AddressingSchemas } from "./addressing/schemas/addressing.schemas.js";

// Fl Service
export { schemas as FlSchemas } from "./fl/schemas/fl.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Jobs Service
export { schemas as JobsSchemas } from "./jobs/schemas/jobs.schemas.js";

// Protocol Service
export { schemas as ProtocolSchemas } from "./protocol/schemas/protocol.schemas.js";

// Provenance Service
export { schemas as ProvenanceSchemas } from "./provenance/schemas/provenance.schemas.js";

// Sites Service
export { schemas as SitesSchemas } from "./sites/schemas/sites.schemas.js";

// Tiers Service
export { schemas as TiersSchemas } from "./tiers/schemas/tiers.schemas.js";

// Trust Service
export { schemas as TrustSchemas } from "./trust/schemas/trust.schemas.js";

