/**
 * Site DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Site DTOs
 *
 * DDD: Application DTOs for Site use cases.
 */

import type { GetSiteParams, ListSitesParams, RegisterSiteRequestInput, UpdateSiteParams, UpdateSiteRequestInput } from "@tierfog/core/sites/types";

export type ListSitesInput = ListSitesParams;

export type RegisterSiteInput = RegisterSiteRequestInput;

export type GetSiteInput = GetSiteParams;

export type UpdateSiteInput = UpdateSiteParams & UpdateSiteRequestInput;

export type ListSitesOutput = {};

export type RegisterSiteOutput = {};

export type GetSiteOutput = {};

export type UpdateSiteOutput = {};
