/**
 * Trust DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Trust Domain Module - Composition root
 *
 * DDD: Composition root for trust domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  JoinRepositoryAdapter,
  QuarantineRepositoryAdapter,
  ReleaseRepositoryAdapter,
  SphereRepositoryAdapter,
  TenantRepositoryAdapter,
} from "@tierfog/adapters/trust";
import { getIdGeneratorService } from "@tierfog/adapters";
import type { AdapterDynamoDBClient } from "@tierfog/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApproveSphereJoin,
  ExecuteCreateTenantSphere,
  ExecuteCreateTrustSphere,
  ExecuteListQuarantineEvents,
  ExecuteListTenantSpheres,
  ExecuteListTrustSpheres,
  ExecuteQuarantineTier,
  ExecuteReleaseQuarantine,
} from "@tierfog/services/trust/usecases";
// Ports (interfaces)
import type {
  JoinRepository,
  QuarantineRepository,
  ReleaseRepository,
  SphereRepository,
  TenantRepository,
} from "@tierfog/services/trust/ports";

export interface TrustDomainModule {
  repos: {
    joins: JoinRepository;
    quarantines: QuarantineRepository;
    releases: ReleaseRepository;
    spheres: SphereRepository;
    tenants: TenantRepository;
  };
  useCases: {
    joins: {
      create: ExecuteApproveSphereJoin;
    };
    quarantines: {
      get: ExecuteQuarantineTier;
      list: ExecuteListQuarantineEvents;
    };
    releases: {
      get: ExecuteReleaseQuarantine;
    };
    spheres: {
      create: ExecuteCreateTrustSphere;
      list: ExecuteListTrustSpheres;
    };
    tenants: {
      create: ExecuteCreateTenantSphere;
      list: ExecuteListTenantSpheres;
    };
  };
}

export function buildTrustDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TrustDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      joins?: JoinRepository;
      quarantines?: QuarantineRepository;
      releases?: ReleaseRepository;
      spheres?: SphereRepository;
      tenants?: TenantRepository;
    } = {};

    obj.joins = new JoinRepositoryAdapter(dynamoClient);
    obj.quarantines = new QuarantineRepositoryAdapter(dynamoClient);
    obj.releases = new ReleaseRepositoryAdapter(dynamoClient);
    obj.spheres = new SphereRepositoryAdapter(dynamoClient);
    obj.tenants = new TenantRepositoryAdapter(dynamoClient);
    return {
      joins: obj.joins!,
      quarantines: obj.quarantines!,
      releases: obj.releases!,
      spheres: obj.spheres!,
      tenants: obj.tenants!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    joins: {
      create: new ExecuteApproveSphereJoin(executionContext, idGenerator, repos.joins),
    },
    quarantines: {
      get: new ExecuteQuarantineTier(executionContext, idGenerator, repos.quarantines),
      list: new ExecuteListQuarantineEvents(executionContext, idGenerator, repos.quarantines),
    },
    releases: {
      get: new ExecuteReleaseQuarantine(executionContext, idGenerator, repos.releases),
    },
    spheres: {
      create: new ExecuteCreateTrustSphere(executionContext, idGenerator, repos.spheres),
      list: new ExecuteListTrustSpheres(executionContext, idGenerator, repos.spheres),
    },
    tenants: {
      create: new ExecuteCreateTenantSphere(executionContext, idGenerator, repos.tenants),
      list: new ExecuteListTenantSpheres(executionContext, idGenerator, repos.tenants),
    },
  };
  return { repos, useCases: useCases as TrustDomainModule["useCases"] };
}
