/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Addressing Domain Use Cases
 * 
 * List of all use case names for the addressing domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ADDRESSING_USE_CASES = [
  "executeGrantDataAddressResolve",
  "executeListDataAddresses",
  "executeRegisterDataAddress",
  "executeRevokeDataAddress"
] as const;
