/**
 * Protocol Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const onboardProtocolDomain_Body = z
  .object({
    protocolFamily: z.enum([
      'mqtt_coap',
      'rpl_6lowpan',
      'bt_mesh',
      'v2x',
      'http_rich',
      'other',
    ]),
    tierId: z.string(),
    gatewayConfigVersion: z.string().optional(),
    isolationChannelClass: z
      .enum(['high_throughput', 'low_power_mesh'])
      .optional(),
  })
  .passthrough();
const pushGatewayConfig_Body = z
  .object({
    configVersion: z.string(),
    rolloutRing: z.enum(['canary', 'ring1', 'ring2', 'all']).optional(),
  })
  .passthrough();
const updateIsolationPolicy_Body = z
  .object({
    highThroughputWeight: z.number().int().gte(0).lte(100),
    lowPowerWeight: z.number().int().gte(0).lte(100),
    stormProtection: z.boolean().optional(),
  })
  .passthrough();

export const schemas: any = {
  onboardProtocolDomain_Body,
  pushGatewayConfig_Body,
  updateIsolationPolicy_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/domains',
    alias: 'listProtocolDomains',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'tierId',
        type: 'Query',
        schema: z.string().optional(),
      },
    ],
    response: z
      .object({
        data: z.object({ items: z.array(z.unknown()) }).passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .and(
            z
              .object({
                pagination: z
                  .object({
                    page: z.number().int().gte(1),
                    limit: z.number().int().gte(1),
                    total: z.number().int().gte(0),
                    cursor: z.string(),
                  })
                  .partial()
                  .passthrough(),
              })
              .partial()
              .passthrough()
          )
          .optional(),
      })
      .passthrough()
      .and(
        z
          .object({
            data: z
              .object({
                items: z.array(
                  z
                    .object({
                      id: z.string().regex(/^prd_[0-9a-z]{26}$/),
                      protocolFamily: z.enum([
                        'mqtt_coap',
                        'rpl_6lowpan',
                        'bt_mesh',
                        'v2x',
                        'http_rich',
                        'other',
                      ]),
                      tierId: z.string(),
                      gatewayConfigVersion: z.string().optional(),
                      status: z.enum([
                        'pending',
                        'healthy',
                        'degraded',
                        'failed',
                      ]),
                      isolationChannelClass: z
                        .enum(['high_throughput', 'low_power_mesh'])
                        .optional(),
                      createdAt: z.string().datetime({ offset: true }),
                      updatedAt: z.string().datetime({ offset: true }),
                    })
                    .passthrough()
                ),
                nextCursor: z.string().optional(),
              })
              .passthrough(),
          })
          .partial()
          .passthrough()
      ),
  },
  {
    method: 'post',
    path: '/v1/domains',
    alias: 'onboardProtocolDomain',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: onboardProtocolDomain_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z.unknown(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough()
      .and(
        z
          .object({
            data: z
              .object({
                id: z.string().regex(/^prd_[0-9a-z]{26}$/),
                protocolFamily: z.enum([
                  'mqtt_coap',
                  'rpl_6lowpan',
                  'bt_mesh',
                  'v2x',
                  'http_rich',
                  'other',
                ]),
                tierId: z.string(),
                gatewayConfigVersion: z.string().optional(),
                status: z.enum(['pending', 'healthy', 'degraded', 'failed']),
                isolationChannelClass: z
                  .enum(['high_throughput', 'low_power_mesh'])
                  .optional(),
                createdAt: z.string().datetime({ offset: true }),
                updatedAt: z.string().datetime({ offset: true }),
              })
              .passthrough(),
          })
          .partial()
          .passthrough()
      ),
  },
  {
    method: 'get',
    path: '/v1/domains/:domainId',
    alias: 'getProtocolDomain',
    requestFormat: 'json',
    parameters: [
      {
        name: 'domainId',
        type: 'Path',
        schema: z.string().regex(/^prd_[0-9a-z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z.unknown(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough()
      .and(
        z
          .object({
            data: z
              .object({
                id: z.string().regex(/^prd_[0-9a-z]{26}$/),
                protocolFamily: z.enum([
                  'mqtt_coap',
                  'rpl_6lowpan',
                  'bt_mesh',
                  'v2x',
                  'http_rich',
                  'other',
                ]),
                tierId: z.string(),
                gatewayConfigVersion: z.string().optional(),
                status: z.enum(['pending', 'healthy', 'degraded', 'failed']),
                isolationChannelClass: z
                  .enum(['high_throughput', 'low_power_mesh'])
                  .optional(),
                createdAt: z.string().datetime({ offset: true }),
                updatedAt: z.string().datetime({ offset: true }),
              })
              .passthrough(),
          })
          .partial()
          .passthrough()
      ),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/domains/:domainId/gateway-config',
    alias: 'pushGatewayConfig',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: pushGatewayConfig_Body,
      },
      {
        name: 'domainId',
        type: 'Path',
        schema: z.string().regex(/^prd_[0-9a-z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z.unknown(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough()
      .and(
        z
          .object({
            data: z
              .object({
                id: z.string().regex(/^prd_[0-9a-z]{26}$/),
                protocolFamily: z.enum([
                  'mqtt_coap',
                  'rpl_6lowpan',
                  'bt_mesh',
                  'v2x',
                  'http_rich',
                  'other',
                ]),
                tierId: z.string(),
                gatewayConfigVersion: z.string().optional(),
                status: z.enum(['pending', 'healthy', 'degraded', 'failed']),
                isolationChannelClass: z
                  .enum(['high_throughput', 'low_power_mesh'])
                  .optional(),
                createdAt: z.string().datetime({ offset: true }),
                updatedAt: z.string().datetime({ offset: true }),
              })
              .passthrough(),
          })
          .partial()
          .passthrough()
      ),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'put',
    path: '/v1/domains/:domainId/isolation',
    alias: 'updateIsolationPolicy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: updateIsolationPolicy_Body,
      },
      {
        name: 'domainId',
        type: 'Path',
        schema: z.string().regex(/^prd_[0-9a-z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z.unknown(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough()
      .and(
        z
          .object({
            data: z
              .object({
                domainId: z.string(),
                highThroughputWeight: z.number().int().gte(0).lte(100),
                lowPowerWeight: z.number().int().gte(0).lte(100),
                stormProtection: z.boolean().optional().default(true),
              })
              .passthrough(),
          })
          .partial()
          .passthrough()
      ),
    errors: [
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.tierfog.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
