/**
 * JoinRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * JoinRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements JoinRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  JoinRepository,
} from "@tierfog/services/trust";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { JoinRepositoryDdb } from "./join-repository.ddb.js";

/**
 * JoinRepositoryAdapter
 *
 * Implements JoinRepository port for infrastructure layer.
 */
export class JoinRepositoryAdapter implements JoinRepository {
  private readonly ddb: JoinRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new JoinRepositoryDdb(this.dynamoClient);
  }

  async approveSphereJoin(input: Parameters<JoinRepository['approveSphereJoin']>[0]): Promise<Awaited<ReturnType<JoinRepository['approveSphereJoin']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.approveSphereJoin(input);
  }
}
