/**
 * ReleaseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReleaseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReleaseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReleaseRepository,
} from "@tierfog/services/trust";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReleaseRepositoryDdb } from "./release-repository.ddb.js";

/**
 * ReleaseRepositoryAdapter
 *
 * Implements ReleaseRepository port for infrastructure layer.
 */
export class ReleaseRepositoryAdapter implements ReleaseRepository {
  private readonly ddb: ReleaseRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReleaseRepositoryDdb(this.dynamoClient);
  }

  async releaseQuarantine(input: Parameters<ReleaseRepository['releaseQuarantine']>[0]): Promise<Awaited<ReturnType<ReleaseRepository['releaseQuarantine']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.releaseQuarantine(input);
  }
}
