/**
 * SphereRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SphereRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SphereRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SphereRepository,
} from "@tierfog/services/trust";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SphereRepositoryDdb } from "./sphere-repository.ddb.js";

/**
 * SphereRepositoryAdapter
 *
 * Implements SphereRepository port for infrastructure layer.
 */
export class SphereRepositoryAdapter implements SphereRepository {
  private readonly ddb: SphereRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SphereRepositoryDdb(this.dynamoClient);
  }

  async listTrustSpheres(input: Parameters<SphereRepository['listTrustSpheres']>[0]): Promise<Awaited<ReturnType<SphereRepository['listTrustSpheres']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTrustSpheres(input);
  }

  async createTrustSphere(input: Parameters<SphereRepository['createTrustSphere']>[0]): Promise<Awaited<ReturnType<SphereRepository['createTrustSphere']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createTrustSphere(input);
  }
}
