/**
 * TenantRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TenantRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TenantRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TenantRepository,
} from "@tierfog/services/trust";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TenantRepositoryDdb } from "./tenant-repository.ddb.js";

/**
 * TenantRepositoryAdapter
 *
 * Implements TenantRepository port for infrastructure layer.
 */
export class TenantRepositoryAdapter implements TenantRepository {
  private readonly ddb: TenantRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TenantRepositoryDdb(this.dynamoClient);
  }

  async listTenantSpheres(input: Parameters<TenantRepository['listTenantSpheres']>[0]): Promise<Awaited<ReturnType<TenantRepository['listTenantSpheres']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTenantSpheres(input);
  }

  async createTenantSphere(input: Parameters<TenantRepository['createTenantSphere']>[0]): Promise<Awaited<ReturnType<TenantRepository['createTenantSphere']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createTenantSphere(input);
  }
}
