/**
 * Sites DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Sites Domain Module - Composition root
 *
 * DDD: Composition root for sites domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  SiteRepositoryAdapter,
} from "@tierfog/adapters/sites";
import { getIdGeneratorService } from "@tierfog/adapters";
import type { AdapterDynamoDBClient } from "@tierfog/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetSite,
  ExecuteListSites,
  ExecuteRegisterSite,
  ExecuteUpdateSite,
} from "@tierfog/services/sites/usecases";
// Ports (interfaces)
import type {
  SiteRepository,
} from "@tierfog/services/sites/ports";

export interface SitesDomainModule {
  repos: {
    sites: SiteRepository;
  };
  useCases: {
    sites: {
      create: ExecuteRegisterSite;
      get: ExecuteGetSite;
      list: ExecuteListSites;
      update: ExecuteUpdateSite;
    };
  };
}

export function buildSitesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SitesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      sites?: SiteRepository;
    } = {};

    obj.sites = new SiteRepositoryAdapter(dynamoClient);
    return {
      sites: obj.sites!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    sites: {
      create: new ExecuteRegisterSite(executionContext, idGenerator, repos.sites),
      get: new ExecuteGetSite(executionContext, idGenerator, repos.sites),
      list: new ExecuteListSites(executionContext, idGenerator, repos.sites),
      update: new ExecuteUpdateSite(executionContext, idGenerator, repos.sites),
    },
  };
  return { repos, useCases: useCases as SitesDomainModule["useCases"] };
}
