/**
 * UpdateIsolationPolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateIsolationPolicy } from "@tierfog/api-server/domains/protocol/handlers";
import type { ProtocolDDDDependencies } from "@tierfog/api-server/domains/protocol";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tierfog/tests/shared";
import { PROTOCOL_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateIsolationPolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProtocolDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProtocolDDDDependencies>(
      PROTOCOL_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { domainId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateIsolationPolicy, "execute").mockResolvedValue(useCaseResult);

    await updateIsolationPolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateIsolationPolicy.execute).toHaveBeenCalledWith(expect.objectContaining({ domainId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
