/**
 * Handlers for Address
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AddressingDomainModule } from "../dependencies/addressing-ddd.dependencies.js";
import type { ListDataAddressesInput, RegisterDataAddressInput } from "@tierfog/services/addressing";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/addresses
 * Operation: listDataAddresses
 */
export async function listDataAddresses(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], owningTierId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AddressingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDataAddressesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.addresses.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/addresses
 * Operation: registerDataAddress
 */
export async function registerDataAddress(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AddressingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterDataAddressInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.addresses.create.execute(input);
  return reply.code(201).send(result);
}


