/**
 * Handlers for Revoke
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AddressingDomainModule } from "../dependencies/addressing-ddd.dependencies.js";
import type { RevokeDataAddressInput } from "@tierfog/services/addressing";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/addresses/{addressId}/revoke
 * Operation: revokeDataAddress
 */
export async function revokeDataAddress(
  request: FastifyRequest<{ Params: { addressId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AddressingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RevokeDataAddressInput = {
    addressId: request.params.addressId,
  };
  const result = await deps.useCases.revokes.get.execute(input);
  return reply.code(200).send(result);
}


