/**
 * EligibilityRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EligibilityRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EligibilityRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EligibilityRepository,
} from "@tierfog/services/fl";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EligibilityRepositoryDdb } from "./eligibility-repository.ddb.js";

/**
 * EligibilityRepositoryAdapter
 *
 * Implements EligibilityRepository port for infrastructure layer.
 */
export class EligibilityRepositoryAdapter implements EligibilityRepository {
  private readonly ddb: EligibilityRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EligibilityRepositoryDdb(this.dynamoClient);
  }

  async listFlRoundEligibility(input: Parameters<EligibilityRepository['listFlRoundEligibility']>[0]): Promise<Awaited<ReturnType<EligibilityRepository['listFlRoundEligibility']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFlRoundEligibility(input);
  }

  async evaluateFlRoundEligibility(input: Parameters<EligibilityRepository['evaluateFlRoundEligibility']>[0]): Promise<Awaited<ReturnType<EligibilityRepository['evaluateFlRoundEligibility']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.evaluateFlRoundEligibility(input);
  }

  async getFlRoundEligibility(input: Parameters<EligibilityRepository['getFlRoundEligibility']>[0]): Promise<Awaited<ReturnType<EligibilityRepository['getFlRoundEligibility']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFlRoundEligibility(input);
  }
}
