/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./eligibility-repository.ddb.js";
export * from "./waive-repository.ddb.js";
export * from "./eligibility-repository.adapter.js";
export * from "./waive-repository.adapter.js";
