/**
 * Handlers for Site
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SitesDomainModule } from "../dependencies/sites-ddd.dependencies.js";
import type { GetSiteInput, ListSitesInput, RegisterSiteInput, UpdateSiteInput } from "@tierfog/services/sites";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/sites
 * Operation: listSites
 */
export async function listSites(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], siteClass?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SitesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSitesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.sites.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/sites
 * Operation: registerSite
 */
export async function registerSite(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SitesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterSiteInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.sites.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/sites/{siteId}
 * Operation: getSite
 */
export async function getSite(
  request: FastifyRequest<{ Params: { siteId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SitesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSiteInput = {
    siteId: request.params.siteId,
  };
  const result = await deps.useCases.sites.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/sites/{siteId}
 * Operation: updateSite
 */
export async function updateSite(
  request: FastifyRequest<{ Params: { siteId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SitesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateSiteInput = {
    siteId: request.params.siteId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.sites.update.execute(input);
  return reply.code(200).send(result);
}


