/**
 * Addressing DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Addressing Domain Module - Composition root
 *
 * DDD: Composition root for addressing domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AddressRepositoryAdapter,
  GrantRepositoryAdapter,
  RevokeRepositoryAdapter,
} from "@tierfog/adapters/addressing";
import { getIdGeneratorService } from "@tierfog/adapters";
import type { AdapterDynamoDBClient } from "@tierfog/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGrantDataAddressResolve,
  ExecuteListDataAddresses,
  ExecuteRegisterDataAddress,
  ExecuteRevokeDataAddress,
} from "@tierfog/services/addressing/usecases";
// Ports (interfaces)
import type {
  AddressRepository,
  GrantRepository,
  RevokeRepository,
} from "@tierfog/services/addressing/ports";

export interface AddressingDomainModule {
  repos: {
    addresses: AddressRepository;
    grants: GrantRepository;
    revokes: RevokeRepository;
  };
  useCases: {
    addresses: {
      create: ExecuteRegisterDataAddress;
      list: ExecuteListDataAddresses;
    };
    grants: {
      get: ExecuteGrantDataAddressResolve;
    };
    revokes: {
      get: ExecuteRevokeDataAddress;
    };
  };
}

export function buildAddressingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AddressingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      addresses?: AddressRepository;
      grants?: GrantRepository;
      revokes?: RevokeRepository;
    } = {};

    obj.addresses = new AddressRepositoryAdapter(dynamoClient);
    obj.grants = new GrantRepositoryAdapter(dynamoClient);
    obj.revokes = new RevokeRepositoryAdapter(dynamoClient);
    return {
      addresses: obj.addresses!,
      grants: obj.grants!,
      revokes: obj.revokes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    addresses: {
      create: new ExecuteRegisterDataAddress(executionContext, idGenerator, repos.addresses),
      list: new ExecuteListDataAddresses(executionContext, idGenerator, repos.addresses),
    },
    grants: {
      get: new ExecuteGrantDataAddressResolve(executionContext, idGenerator, repos.grants),
    },
    revokes: {
      get: new ExecuteRevokeDataAddress(executionContext, idGenerator, repos.revokes),
    },
  };
  return { repos, useCases: useCases as AddressingDomainModule["useCases"] };
}
