/**
 * DomainRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DomainRepository Port
 *
 * DDD: Application port for domainrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetProtocolDomainInput, GetProtocolDomainOutput, ListProtocolDomainsInput, ListProtocolDomainsOutput, OnboardProtocolDomainInput, OnboardProtocolDomainOutput } from "../dto/domain.dto";
export interface DomainRepository {
  listProtocolDomains(input: ListProtocolDomainsInput): Promise<ListProtocolDomainsOutput>;
  onboardProtocolDomain(input: OnboardProtocolDomainInput): Promise<OnboardProtocolDomainOutput>;
  getProtocolDomain(input: GetProtocolDomainInput): Promise<GetProtocolDomainOutput>;
}

export type { GetProtocolDomainInput, GetProtocolDomainOutput, ListProtocolDomainsInput, ListProtocolDomainsOutput, OnboardProtocolDomainInput, OnboardProtocolDomainOutput } from "../dto/domain.dto";
