/**
 * GatewayConfigRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GatewayConfigRepository Port
 *
 * DDD: Application port for gatewayconfigrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PushGatewayConfigInput, PushGatewayConfigOutput } from "../dto/gateway-config.dto";
export interface GatewayConfigRepository {
  pushGatewayConfig(input: PushGatewayConfigInput): Promise<PushGatewayConfigOutput>;
}

export type { PushGatewayConfigInput, PushGatewayConfigOutput } from "../dto/gateway-config.dto";
