/**
 * IsolationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IsolationRepository Port
 *
 * DDD: Application port for isolationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { UpdateIsolationPolicyInput, UpdateIsolationPolicyOutput } from "../dto/isolation.dto";
export interface IsolationRepository {
  updateIsolationPolicy(input: UpdateIsolationPolicyInput): Promise<UpdateIsolationPolicyOutput>;
}

export type { UpdateIsolationPolicyInput, UpdateIsolationPolicyOutput } from "../dto/isolation.dto";
