/**
 * Address DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Address DTOs
 *
 * DDD: Application DTOs for Address use cases.
 */

import type { ListDataAddressesParams, RegisterDataAddressRequestInput } from "@tierfog/core/addressing/types";

export type ListDataAddressesInput = ListDataAddressesParams;

export type RegisterDataAddressInput = RegisterDataAddressRequestInput;

export type ListDataAddressesOutput = {};

export type RegisterDataAddressOutput = {};
