/**
 * Grant DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Grant DTOs
 *
 * DDD: Application DTOs for Grant use cases.
 */

import type { GrantDataAddressResolveParams, GrantDataAddressResolveRequestInput } from "@tierfog/core/addressing/types";

export type GrantDataAddressResolveInput = GrantDataAddressResolveParams & GrantDataAddressResolveRequestInput;

export type GrantDataAddressResolveOutput = {};
