/**
 * Domain DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Domain DTOs
 *
 * DDD: Application DTOs for Domain use cases.
 */

import type { GetProtocolDomainParams, ListProtocolDomainsParams, OnboardProtocolDomainRequestInput } from "@tierfog/core/protocol/types";

export type ListProtocolDomainsInput = ListProtocolDomainsParams;

export type OnboardProtocolDomainInput = OnboardProtocolDomainRequestInput;

export type GetProtocolDomainInput = GetProtocolDomainParams;

export type ListProtocolDomainsOutput = {};

export type OnboardProtocolDomainOutput = {};

export type GetProtocolDomainOutput = {};
