/**
 * GatewayConfig DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: protocol
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GatewayConfig DTOs
 *
 * DDD: Application DTOs for GatewayConfig use cases.
 */

import type { PushGatewayConfigParams, PushGatewayConfigRequestInput } from "@tierfog/core/protocol/types";

export type PushGatewayConfigInput = PushGatewayConfigParams & PushGatewayConfigRequestInput;

export type PushGatewayConfigOutput = {};
