/**
 * GetFlRoundEligibility handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getFlRoundEligibility } from "@tierfog/api-server/domains/fl/handlers";
import type { FlDDDDependencies } from "@tierfog/api-server/domains/fl";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tierfog/tests/shared";
import { FL_USE_CASES } from "../__factories__/use-cases.js";

describe("GetFlRoundEligibility", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FlDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FlDDDDependencies>(
      FL_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetFlRoundEligibility, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { eligibilityId: entity.id };

    await getFlRoundEligibility(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetFlRoundEligibility.execute).toHaveBeenCalledWith(expect.objectContaining({ eligibilityId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { eligibilityId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetFlRoundEligibility, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getFlRoundEligibility(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
