/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./get-site.handler.test.js";
export * from "./list-sites.handler.test.js";
export * from "./register-site.handler.test.js";
export * from "./update-site.handler.test.js";
