/**
 * ListSites handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listSites } from "@tierfog/api-server/domains/sites/handlers";
import type { SitesDDDDependencies } from "@tierfog/api-server/domains/sites";
import { createSite as createSiteEntity } from "@tierfog/factories/sites";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tierfog/tests/shared";
import { SITES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListSites", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SitesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SitesDDDDependencies>(
      SITES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createSiteEntity({ orgId }),
      createSiteEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListSites, "execute").mockResolvedValue(useCaseResult);

    await listSites(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListSites.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
