/**
 * UpdateSite handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateSite } from "@tierfog/api-server/domains/sites/handlers";
import type { SitesDDDDependencies } from "@tierfog/api-server/domains/sites";
import { createSite as createSiteEntity } from "@tierfog/factories/sites";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tierfog/tests/shared";
import { SITES_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateSite", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SitesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SitesDDDDependencies>(
      SITES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createSiteEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { siteId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateSite, "execute").mockResolvedValue(useCaseResult);

    await updateSite(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateSite.execute).toHaveBeenCalledWith(expect.objectContaining({ siteId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
