/**
 * ProvenanceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProvenanceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ProvenanceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ProvenanceRepository,
} from "@tierfog/services/provenance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ProvenanceRepositoryDdb } from "./provenance-repository.ddb.js";

/**
 * ProvenanceRepositoryAdapter
 *
 * Implements ProvenanceRepository port for infrastructure layer.
 */
export class ProvenanceRepositoryAdapter implements ProvenanceRepository {
  private readonly ddb: ProvenanceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ProvenanceRepositoryDdb(this.dynamoClient);
  }

  async listArtefactProvenance(input: Parameters<ProvenanceRepository['listArtefactProvenance']>[0]): Promise<Awaited<ReturnType<ProvenanceRepository['listArtefactProvenance']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listArtefactProvenance(input);
  }

  async sealArtefactProvenance(input: Parameters<ProvenanceRepository['sealArtefactProvenance']>[0]): Promise<Awaited<ReturnType<ProvenanceRepository['sealArtefactProvenance']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.sealArtefactProvenance(input);
  }

  async getArtefactProvenance(input: Parameters<ProvenanceRepository['getArtefactProvenance']>[0]): Promise<Awaited<ReturnType<ProvenanceRepository['getArtefactProvenance']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getArtefactProvenance(input);
  }
}
