/**
 * GetProvenance DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetArtefactProvenanceParams } from "@tierfog/core/provenance";

export function createGetProvenanceRequest(overrides: Partial<GetArtefactProvenanceParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
