/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAddressingDomainModule } from "./addressing/dependencies/addressing-ddd.dependencies.js";
export { buildFlDomainModule } from "./fl/dependencies/fl-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildJobsDomainModule } from "./jobs/dependencies/jobs-ddd.dependencies.js";
export { buildProtocolDomainModule } from "./protocol/dependencies/protocol-ddd.dependencies.js";
export { buildProvenanceDomainModule } from "./provenance/dependencies/provenance-ddd.dependencies.js";
export { buildSitesDomainModule } from "./sites/dependencies/sites-ddd.dependencies.js";
export { buildTiersDomainModule } from "./tiers/dependencies/tiers-ddd.dependencies.js";
export { buildTrustDomainModule } from "./trust/dependencies/trust-ddd.dependencies.js";

// Export all domain dependency types
export type { AddressingDomainModule } from "./addressing/dependencies/addressing-ddd.dependencies.js";
export type { FlDomainModule } from "./fl/dependencies/fl-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { JobsDomainModule } from "./jobs/dependencies/jobs-ddd.dependencies.js";
export type { ProtocolDomainModule } from "./protocol/dependencies/protocol-ddd.dependencies.js";
export type { ProvenanceDomainModule } from "./provenance/dependencies/provenance-ddd.dependencies.js";
export type { SitesDomainModule } from "./sites/dependencies/sites-ddd.dependencies.js";
export type { TiersDomainModule } from "./tiers/dependencies/tiers-ddd.dependencies.js";
export type { TrustDomainModule } from "./trust/dependencies/trust-ddd.dependencies.js";
