/**
 * Routes for Eligibility
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { evaluateFlRoundEligibility, getFlRoundEligibility, listFlRoundEligibility } from "../handlers/eligibility.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function eligibilityRoutes(fastify: FastifyInstance) {
  // POST /v1/fl/eligibility (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/fl/eligibility",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFlDependenciesForRequest();
        await evaluateFlRoundEligibility(request, reply, deps);
      });
    }
  );


  // GET /v1/fl/eligibility (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/fl/eligibility",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFlDependenciesForRequest();
        await listFlRoundEligibility(request, reply, deps);
      });
    }
  );


  // GET /v1/fl/eligibility/{eligibilityId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/fl/eligibility/:eligibilityId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { eligibilityId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFlDependenciesForRequest();
        await getFlRoundEligibility(request, reply, deps);
      });
    }
  );


}
