/**
 * Routes for Waive
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { waiveFlHealthGate } from "../handlers/waive.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function waiveRoutes(fastify: FastifyInstance) {
  // POST /v1/fl/eligibility/{eligibilityId}/waive (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/fl/eligibility/:eligibilityId/waive",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { eligibilityId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFlDependenciesForRequest();
        await waiveFlHealthGate(request, reply, deps);
      });
    }
  );


}
