/**
 * ExecuteListTiers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListTiers Use Case
 *
 * DDD: Application use case for list Tier.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListTiersInput, ListTiersOutput } from "../dto/tier.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { TierRepository } from "../ports";

export class ExecuteListTiers {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly tier: TierRepository
  ) {}

  async execute(input: ListTiersInput): Promise<ListTiersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tirId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.tier.listTiers({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListTiersOutput;
  }
}
