/**
 * Join DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Join DTOs
 *
 * DDD: Application DTOs for Join use cases.
 */

import type { ApproveSphereJoinParams, ApproveSphereJoinRequestInput } from "@tierfog/core/trust/types";

export type ApproveSphereJoinInput = ApproveSphereJoinParams & ApproveSphereJoinRequestInput;

export type ApproveSphereJoinOutput = {};
