/**
 * Quarantine DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Quarantine DTOs
 *
 * DDD: Application DTOs for Quarantine use cases.
 */

import type { ListQuarantineEventsParams, QuarantineTierRequestInput } from "@tierfog/core/trust/types";

export type ListQuarantineEventsInput = ListQuarantineEventsParams;

export type QuarantineTierInput = QuarantineTierRequestInput;

export type ListQuarantineEventsOutput = {};

export type QuarantineTierOutput = {};
