/**
 * Sphere DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Sphere DTOs
 *
 * DDD: Application DTOs for Sphere use cases.
 */

import type { CreateTrustSphereRequestInput, ListTrustSpheresParams } from "@tierfog/core/trust/types";

export type ListTrustSpheresInput = ListTrustSpheresParams;

export type CreateTrustSphereInput = CreateTrustSphereRequestInput;

export type ListTrustSpheresOutput = {};

export type CreateTrustSphereOutput = {};
