/**
 * Tenant DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Tenant DTOs
 *
 * DDD: Application DTOs for Tenant use cases.
 */

import type { CreateTenantSphereRequestInput, ListTenantSpheresParams } from "@tierfog/core/trust/types";

export type ListTenantSpheresInput = ListTenantSpheresParams;

export type CreateTenantSphereInput = CreateTenantSphereRequestInput;

export type ListTenantSpheresOutput = {};

export type CreateTenantSphereOutput = {};
