/**
 * ExecuteOverrideJobPlacement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOverrideJobPlacement Use Case
 *
 * DDD: Application use case for get OverridePlacement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OverrideJobPlacementInput, OverrideJobPlacementOutput } from "../dto/override-placement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { OverridePlacementRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteOverrideJobPlacement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly overridePlacement: OverridePlacementRepository
  ) {}

  async execute(input: OverrideJobPlacementInput): Promise<OverrideJobPlacementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.jobId();

    // All field names extracted from OpenAPI spec: executionTierId, reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).jobId) {
      throw new ValidationError("jobId is required");
    }
    const jobId = (input as any).jobId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.overridePlacement.overrideJobPlacement({ jobId: jobId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${jobId}`);
    }

    return entity as OverrideJobPlacementOutput;
  }
}
