/**
 * ExecuteScheduleAnalyticsJob - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteScheduleAnalyticsJob Use Case
 *
 * DDD: Application use case for get Job.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ScheduleAnalyticsJobInput, ScheduleAnalyticsJobOutput } from "../dto/job.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { JobRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteScheduleAnalyticsJob {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly job: JobRepository
  ) {}

  async execute(input: ScheduleAnalyticsJobInput): Promise<ScheduleAnalyticsJobOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.jobId();

    // All field names extracted from OpenAPI spec: flRoundId, preferredMaxTierRole, siteId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).flRoundId) {
      throw new ValidationError("flRoundId is required");
    }
    const flroundId = (input as any).flRoundId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.job.scheduleAnalyticsJob({ flRoundId: flroundId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${flroundId}`);
    }

    return entity as ScheduleAnalyticsJobOutput;
  }
}
