/**
 * Site Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/sites.openapi.types.js";
import { schemas } from "../schemas/sites.schemas.js";

/**
 * Entity: SiteEntity
 * Description: Represents the Site domain model.
 * Source: schemas.Site
 * Type: Domain Entity (API)
 */
export const SiteEntitySchema = schemas.Site;
export type SiteEntity = components["schemas"]["Site"];
