/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Fl Domain Use Cases
 * 
 * List of all use case names for the fl domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const FL_USE_CASES = [
  "executeEvaluateFlRoundEligibility",
  "executeGetFlRoundEligibility",
  "executeListFlRoundEligibility",
  "executeWaiveFlHealthGate"
] as const;
