/**
 * Repository interface for Site
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SiteEntity
} from "../models/site.entity.js";
import type {
  ListSitesParams,
  Site,
  UpdateSiteRequestInput
} from "../types/index.js";
/**
 * SiteRepository Interface
 */
export interface SiteRepository extends CreateUpdateReadRepository<SiteEntity, Site, UpdateSiteRequestInput, string, ListSitesParams> {

}
