/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Trust Domain Use Cases
 * 
 * List of all use case names for the trust domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const TRUST_USE_CASES = [
  "executeApproveSphereJoin",
  "executeCreateTenantSphere",
  "executeCreateTrustSphere",
  "executeListQuarantineEvents",
  "executeListTenantSpheres",
  "executeListTrustSpheres",
  "executeQuarantineTier",
  "executeReleaseQuarantine"
] as const;
