/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@tierfog/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@tierfog/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@tierfog/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _addressing from "./addressing/index.js";
import * as _fl from "./fl/index.js";
import * as _identity from "./identity/index.js";
import * as _jobs from "./jobs/index.js";
import * as _protocol from "./protocol/index.js";
import * as _provenance from "./provenance/index.js";
import * as _sites from "./sites/index.js";
import * as _tiers from "./tiers/index.js";
import * as _trust from "./trust/index.js";

// Export as namespaces
export const addressing = _addressing;
export const fl = _fl;
export const identity = _identity;
export const jobs = _jobs;
export const protocol = _protocol;
export const provenance = _provenance;
export const sites = _sites;
export const tiers = _tiers;
export const trust = _trust;
