/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Tiers Domain Use Cases
 * 
 * List of all use case names for the tiers domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const TIERS_USE_CASES = [
  "executeGetTier",
  "executeListTiers",
  "executeRegisterTier"
] as const;
