/**
 * JoinRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * JoinRepository Port
 *
 * DDD: Application port for joinrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ApproveSphereJoinInput, ApproveSphereJoinOutput } from "../dto/join.dto";
export interface JoinRepository {
  approveSphereJoin(input: ApproveSphereJoinInput): Promise<ApproveSphereJoinOutput>;
}

export type { ApproveSphereJoinInput, ApproveSphereJoinOutput } from "../dto/join.dto";
