/**
 * QuarantineRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * QuarantineRepository Port
 *
 * DDD: Application port for quarantinerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListQuarantineEventsInput, ListQuarantineEventsOutput, QuarantineTierInput, QuarantineTierOutput } from "../dto/quarantine.dto";
export interface QuarantineRepository {
  listQuarantineEvents(input: ListQuarantineEventsInput): Promise<ListQuarantineEventsOutput>;
  quarantineTier(input: QuarantineTierInput): Promise<QuarantineTierOutput>;
}

export type { ListQuarantineEventsInput, ListQuarantineEventsOutput, QuarantineTierInput, QuarantineTierOutput } from "../dto/quarantine.dto";
