/**
 * SphereRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SphereRepository Port
 *
 * DDD: Application port for sphererepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateTrustSphereInput, CreateTrustSphereOutput, ListTrustSpheresInput, ListTrustSpheresOutput } from "../dto/sphere.dto";
export interface SphereRepository {
  listTrustSpheres(input: ListTrustSpheresInput): Promise<ListTrustSpheresOutput>;
  createTrustSphere(input: CreateTrustSphereInput): Promise<CreateTrustSphereOutput>;
}

export type { CreateTrustSphereInput, CreateTrustSphereOutput, ListTrustSpheresInput, ListTrustSpheresOutput } from "../dto/sphere.dto";
