/**
 * TenantRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TenantRepository Port
 *
 * DDD: Application port for tenantrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateTenantSphereInput, CreateTenantSphereOutput, ListTenantSpheresInput, ListTenantSpheresOutput } from "../dto/tenant.dto";
export interface TenantRepository {
  listTenantSpheres(input: ListTenantSpheresInput): Promise<ListTenantSpheresOutput>;
  createTenantSphere(input: CreateTenantSphereInput): Promise<CreateTenantSphereOutput>;
}

export type { CreateTenantSphereInput, CreateTenantSphereOutput, ListTenantSpheresInput, ListTenantSpheresOutput } from "../dto/tenant.dto";
