/**
 * ListJob DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAnalyticsJobsParams } from "@tierfog/core/jobs";

export function createListJobRequest(overrides: Partial<ListAnalyticsJobsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
