/**
 * Handlers for Job
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { JobsDomainModule } from "../dependencies/jobs-ddd.dependencies.js";
import type { GetAnalyticsJobInput, ListAnalyticsJobsInput, ScheduleAnalyticsJobInput } from "@tierfog/services/jobs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/jobs
 * Operation: listAnalyticsJobs
 */
export async function listAnalyticsJobs(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: JobsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAnalyticsJobsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.jobs.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/jobs
 * Operation: scheduleAnalyticsJob
 */
export async function scheduleAnalyticsJob(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: JobsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ScheduleAnalyticsJobInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.jobs.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/jobs/{jobId}
 * Operation: getAnalyticsJob
 */
export async function getAnalyticsJob(
  request: FastifyRequest<{ Params: { jobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: JobsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAnalyticsJobInput = {
    jobId: request.params.jobId,
  };
  const result = await deps.useCases.jobs.get.execute(input);
  return reply.code(200).send(result);
}


