/**
 * ExecuteRevokeDataAddress - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRevokeDataAddress Use Case
 *
 * DDD: Application use case for get Revoke.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RevokeDataAddressInput, RevokeDataAddressOutput } from "../dto/revoke.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { RevokeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRevokeDataAddress {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly revoke: RevokeRepository
  ) {}

  async execute(input: RevokeDataAddressInput): Promise<RevokeDataAddressOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.adrId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).addressId) {
      throw new ValidationError("addressId is required");
    }
    const addressId = (input as any).addressId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.revoke.revokeDataAddress({ addressId: addressId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${addressId}`);
    }

    return entity as RevokeDataAddressOutput;
  }
}
