/**
 * ExecuteRegisterDataAddress - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterDataAddress Use Case
 *
 * DDD: Application use case for create Address.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterDataAddressInput, RegisterDataAddressOutput } from "../dto/address.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { AddressRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterDataAddress {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly address: AddressRepository
  ) {}

  async execute(input: RegisterDataAddressInput): Promise<RegisterDataAddressOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.adrId();

    // All field names extracted from OpenAPI spec: owningTierId, ref
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.ref) {
      throw new ValidationError("ref is required");
    }
    if (!input.owningTierId) {
      throw new ValidationError("owningTierId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (addressing domain)
    const entityId = this.idGenerator.adrId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.address.registerDataAddress({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterDataAddressOutput;
  }
}
