/**
 * ExecuteListDataAddresses - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDataAddresses Use Case
 *
 * DDD: Application use case for list Address.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDataAddressesInput, ListDataAddressesOutput } from "../dto/address.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { AddressRepository } from "../ports";

export class ExecuteListDataAddresses {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly address: AddressRepository
  ) {}

  async execute(input: ListDataAddressesInput): Promise<ListDataAddressesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.adrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.address.listDataAddresses({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDataAddressesOutput;
  }
}
