/**
 * Tier DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Tier DTOs
 *
 * DDD: Application DTOs for Tier use cases.
 */

import type { GetTierParams, ListTiersParams, RegisterTierRequestInput } from "@tierfog/core/tiers/types";

export type ListTiersInput = ListTiersParams;

export type RegisterTierInput = RegisterTierRequestInput;

export type GetTierInput = GetTierParams;

export type ListTiersOutput = {};

export type RegisterTierOutput = {};

export type GetTierOutput = {};
