/**
 * ListAnalyticsJobs handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listAnalyticsJobs } from "@tierfog/api-server/domains/jobs/handlers";
import type { JobsDDDDependencies } from "@tierfog/api-server/domains/jobs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tierfog/tests/shared";
import { JOBS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListAnalyticsJobs", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: JobsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<JobsDDDDependencies>(
      JOBS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      { id: 'mock-1', orgId } as any,
      { id: 'mock-2', orgId } as any,
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListAnalyticsJobs, "execute").mockResolvedValue(useCaseResult);

    await listAnalyticsJobs(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListAnalyticsJobs.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
