/**
 * RevokeDataAddress handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { revokeDataAddress } from "@tierfog/api-server/domains/addressing/handlers";
import type { AddressingDDDDependencies } from "@tierfog/api-server/domains/addressing";
import { createCreateRevokeRequest } from "@tierfog/factories/addressing";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tierfog/tests/shared";
import { ADDRESSING_USE_CASES } from "../__factories__/use-cases.js";

describe("RevokeDataAddress", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AddressingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AddressingDDDDependencies>(
      ADDRESSING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateRevokeRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRevokeDataAddress, "execute").mockResolvedValue(useCaseResult);

    await revokeDataAddress(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRevokeDataAddress.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
