/**
 * TierRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TierRepository Port
 *
 * DDD: Application port for tierrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetTierInput, GetTierOutput, ListTiersInput, ListTiersOutput, RegisterTierInput, RegisterTierOutput } from "../dto/tier.dto";
export interface TierRepository {
  listTiers(input: ListTiersInput): Promise<ListTiersOutput>;
  registerTier(input: RegisterTierInput): Promise<RegisterTierOutput>;
  getTier(input: GetTierInput): Promise<GetTierOutput>;
}

export type { GetTierInput, GetTierOutput, ListTiersInput, ListTiersOutput, RegisterTierInput, RegisterTierOutput } from "../dto/tier.dto";
