/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { quarantineRoutes } from "./quarantine.routes.js";
export { sphereRoutes } from "./sphere.routes.js";
export { tenantRoutes } from "./tenant.routes.js";
export { joinRoutes } from "./join.routes.js";
export { releaseRoutes } from "./release.routes.js";
