/**
 * Routes for Join
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trust
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { approveSphereJoin } from "../handlers/join.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function joinRoutes(fastify: FastifyInstance) {
  // POST /v1/trust/spheres/{sphereId}/join (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/trust/spheres/:sphereId/join",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { sphereId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTrustDependenciesForRequest();
        await approveSphereJoin(request, reply, deps);
      });
    }
  );


}
