/**
 * ExecuteWaiveFlHealthGate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteWaiveFlHealthGate Use Case
 *
 * DDD: Application use case for get Waive.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { WaiveFlHealthGateInput, WaiveFlHealthGateOutput } from "../dto/waive.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { WaiveRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteWaiveFlHealthGate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly waive: WaiveRepository
  ) {}

  async execute(input: WaiveFlHealthGateInput): Promise<WaiveFlHealthGateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.flrId();

    // All field names extracted from OpenAPI spec: waiverNote
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).eligibilityId) {
      throw new ValidationError("eligibilityId is required");
    }
    const eligibilityId = (input as any).eligibilityId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.waive.waiveFlHealthGate({ eligibilityId: eligibilityId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${eligibilityId}`);
    }

    return entity as WaiveFlHealthGateOutput;
  }
}
