/**
 * ExecuteGetFlRoundEligibility - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetFlRoundEligibility Use Case
 *
 * DDD: Application use case for get Eligibility.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetFlRoundEligibilityInput, GetFlRoundEligibilityOutput } from "../dto/eligibility.dto";
import type { ExecutionContextService, IdGeneratorService } from "@tierfog/services/_shared/index.js";
import type { EligibilityRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetFlRoundEligibility {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly eligibility: EligibilityRepository
  ) {}

  async execute(input: GetFlRoundEligibilityInput): Promise<GetFlRoundEligibilityOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.flrId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).eligibilityId) {
      throw new ValidationError("eligibilityId is required");
    }
    const eligibilityId = (input as any).eligibilityId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.eligibility.getFlRoundEligibility({ eligibilityId: eligibilityId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${eligibilityId}`);
    }

    return entity as GetFlRoundEligibilityOutput;
  }
}
