/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Sites Domain Use Cases
 * 
 * List of all use case names for the sites domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SITES_USE_CASES = [
  "executeGetSite",
  "executeListSites",
  "executeRegisterSite",
  "executeUpdateSite"
] as const;
