/**
 * ListTier DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListTiersParams } from "@tierfog/core/tiers";

export function createListTierRequest(overrides: Partial<ListTiersParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
