/**
 * Provenance DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Provenance Domain Module - Composition root
 *
 * DDD: Composition root for provenance domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ProvenanceRepositoryAdapter,
} from "@tierfog/adapters/provenance";
import { getIdGeneratorService } from "@tierfog/adapters";
import type { AdapterDynamoDBClient } from "@tierfog/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetArtefactProvenance,
  ExecuteListArtefactProvenance,
  ExecuteSealArtefactProvenance,
} from "@tierfog/services/provenance/usecases";
// Ports (interfaces)
import type {
  ProvenanceRepository,
} from "@tierfog/services/provenance/ports";

export interface ProvenanceDomainModule {
  repos: {
    provenances: ProvenanceRepository;
  };
  useCases: {
    provenances: {
      get: ExecuteGetArtefactProvenance;
      list: ExecuteListArtefactProvenance;
    };
  };
}

export function buildProvenanceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ProvenanceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      provenances?: ProvenanceRepository;
    } = {};

    obj.provenances = new ProvenanceRepositoryAdapter(dynamoClient);
    return {
      provenances: obj.provenances!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    provenances: {
      get: new ExecuteGetArtefactProvenance(executionContext, idGenerator, repos.provenances),
      list: new ExecuteListArtefactProvenance(executionContext, idGenerator, repos.provenances),
    },
  };
  return { repos, useCases: useCases as ProvenanceDomainModule["useCases"] };
}
