/**
 * Routes for Site
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: sites
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getSite, listSites, registerSite, updateSite } from "../handlers/site.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function siteRoutes(fastify: FastifyInstance) {
  // GET /v1/sites (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/sites",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSitesDependenciesForRequest();
        await listSites(request, reply, deps);
      });
    }
  );


  // POST /v1/sites (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/sites",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSitesDependenciesForRequest();
        await registerSite(request, reply, deps);
      });
    }
  );


  // GET /v1/sites/{siteId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/sites/:siteId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { siteId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSitesDependenciesForRequest();
        await getSite(request, reply, deps);
      });
    }
  );


  // PATCH /v1/sites/{siteId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/sites/:siteId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { siteId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSitesDependenciesForRequest();
        await updateSite(request, reply, deps);
      });
    }
  );


}
