/**
 * RegisterTier handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { registerTier } from "@tierfog/api-server/domains/tiers/handlers";
import type { TiersDDDDependencies } from "@tierfog/api-server/domains/tiers";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@tierfog/tests/shared";
import { TIERS_USE_CASES } from "../__factories__/use-cases.js";

describe("RegisterTier", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TiersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TiersDDDDependencies>(
      TIERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRegisterTier, "execute").mockResolvedValue(useCaseResult);

    await registerTier(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRegisterTier.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
