/**
 * Handlers for Eligibility
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { FlDomainModule } from "../dependencies/fl-ddd.dependencies.js";
import type { EvaluateFlRoundEligibilityInput, GetFlRoundEligibilityInput, ListFlRoundEligibilityInput } from "@tierfog/services/fl";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/fl/eligibility
 * Operation: listFlRoundEligibility
 */
export async function listFlRoundEligibility(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], roundId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: FlDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListFlRoundEligibilityInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.eligibilities.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/fl/eligibility
 * Operation: evaluateFlRoundEligibility
 */
export async function evaluateFlRoundEligibility(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: FlDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: EvaluateFlRoundEligibilityInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.eligibilities.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/fl/eligibility/{eligibilityId}
 * Operation: getFlRoundEligibility
 */
export async function getFlRoundEligibility(
  request: FastifyRequest<{ Params: { eligibilityId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: FlDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetFlRoundEligibilityInput = {
    eligibilityId: request.params.eligibilityId,
  };
  const result = await deps.useCases.eligibilities.get.execute(input);
  return reply.code(200).send(result);
}


