/**
 * Fl DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fl
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Fl Domain Module - Composition root
 *
 * DDD: Composition root for fl domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EligibilityRepositoryAdapter,
  WaiveRepositoryAdapter,
} from "@tierfog/adapters/fl";
import { getIdGeneratorService } from "@tierfog/adapters";
import type { AdapterDynamoDBClient } from "@tierfog/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteEvaluateFlRoundEligibility,
  ExecuteGetFlRoundEligibility,
  ExecuteListFlRoundEligibility,
  ExecuteWaiveFlHealthGate,
} from "@tierfog/services/fl/usecases";
// Ports (interfaces)
import type {
  EligibilityRepository,
  WaiveRepository,
} from "@tierfog/services/fl/ports";

export interface FlDomainModule {
  repos: {
    eligibilities: EligibilityRepository;
    waives: WaiveRepository;
  };
  useCases: {
    eligibilities: {
      create: ExecuteEvaluateFlRoundEligibility;
      get: ExecuteGetFlRoundEligibility;
      list: ExecuteListFlRoundEligibility;
    };
    waives: {
      get: ExecuteWaiveFlHealthGate;
    };
  };
}

export function buildFlDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): FlDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      eligibilities?: EligibilityRepository;
      waives?: WaiveRepository;
    } = {};

    obj.eligibilities = new EligibilityRepositoryAdapter(dynamoClient);
    obj.waives = new WaiveRepositoryAdapter(dynamoClient);
    return {
      eligibilities: obj.eligibilities!,
      waives: obj.waives!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    eligibilities: {
      create: new ExecuteEvaluateFlRoundEligibility(executionContext, idGenerator, repos.eligibilities),
      get: new ExecuteGetFlRoundEligibility(executionContext, idGenerator, repos.eligibilities),
      list: new ExecuteListFlRoundEligibility(executionContext, idGenerator, repos.eligibilities),
    },
    waives: {
      get: new ExecuteWaiveFlHealthGate(executionContext, idGenerator, repos.waives),
    },
  };
  return { repos, useCases: useCases as FlDomainModule["useCases"] };
}
