/**
 * CreatePause DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { PauseAnalyticsJobParams } from "@tierfog/core/jobs";

export function createCreatePauseRequest(overrides: Partial<PauseAnalyticsJobParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
