/**
 * Routes for Address
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listDataAddresses, registerDataAddress } from "../handlers/address.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function addressRoutes(fastify: FastifyInstance) {
  // GET /v1/addresses (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/addresses",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAddressingDependenciesForRequest();
        await listDataAddresses(request, reply, deps);
      });
    }
  );


  // POST /v1/addresses (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/addresses",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAddressingDependenciesForRequest();
        await registerDataAddress(request, reply, deps);
      });
    }
  );


}
