/**
 * Routes for Grant
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { grantDataAddressResolve } from "../handlers/grant.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function grantRoutes(fastify: FastifyInstance) {
  // POST /v1/addresses/{addressId}/grant (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/addresses/:addressId/grant",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { addressId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAddressingDependenciesForRequest();
        await grantDataAddressResolve(request, reply, deps);
      });
    }
  );


}
