/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: addressing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { addressRoutes } from "./address.routes.js";
export { grantRoutes } from "./grant.routes.js";
export { revokeRoutes } from "./revoke.routes.js";
